/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.bank.management.system;
import java.awt.event.*;
import javax.swing.*;


/**
 *
 * @author ACER
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_reports = new javax.swing.JButton();
        btn_searchdonor = new javax.swing.JButton();
        btn_receiver = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_bstock = new javax.swing.JButton();
        btn_Hexit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_admin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setName("HomeForm"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reports.setBackground(new java.awt.Color(153, 153, 153));
        btn_reports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reports.setText("Reports");
        getContentPane().add(btn_reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 180, 40));

        btn_searchdonor.setBackground(new java.awt.Color(153, 153, 153));
        btn_searchdonor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_searchdonor.setText("Add New Donor");
        btn_searchdonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchdonorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_searchdonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, 40));

        btn_receiver.setBackground(new java.awt.Color(153, 153, 153));
        btn_receiver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_receiver.setText("Reciever Details");
        getContentPane().add(btn_receiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 40));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Search Donor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, 40));

        btn_bstock.setBackground(new java.awt.Color(153, 153, 153));
        btn_bstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_bstock.setText("Blood Unit Stocks");
        getContentPane().add(btn_bstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 180, 40));

        btn_Hexit.setBackground(new java.awt.Color(153, 153, 153));
        btn_Hexit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Hexit.setForeground(new java.awt.Color(102, 0, 0));
        btn_Hexit.setText("EXIT");
        btn_Hexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HexitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Hexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, 90, 30));

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText(" Blood  Bank  Management  System");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 940, 60));

        jLabel1.setText("Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 30));

        txt_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adminActionPerformed(evt);
            }
        });
        getContentPane().add(txt_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\My Java\\BloodBankLogos\\ltt.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 330, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HexitActionPerformed
        // TODO add your handling code here:
        try
        {
         int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) 
            {
            Login loginform = new Login();
            loginform.setVisible(true);
            dispose();
            
           }
            if (confirm == javax.swing.JOptionPane.NO_OPTION) 
                    {
                        new Homepage().setVisible(true);
                    }
                    
        }
        catch(Exception e)
        {
          System.out.println("Error! Try Again" + e.getMessage());
        }
          
        
    }//GEN-LAST:event_btn_HexitActionPerformed

    private void btn_searchdonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchdonorActionPerformed
        // TODO add your handling code here
       DonorRegister dr= new DonorRegister();
       dr.setVisible(true);
    }//GEN-LAST:event_btn_searchdonorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adminActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txt_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Hexit;
    private javax.swing.JButton btn_bstock;
    private javax.swing.JButton btn_receiver;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_searchdonor;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_admin;
    // End of variables declaration//GEN-END:variables
}
