/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.bank.management.system;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_upassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        btn_Logintohome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(255, 255, 204));
        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 150, 30));

        txt_upassword.setBackground(new java.awt.Color(255, 255, 204));
        txt_upassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_upassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_upassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, 30));

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText(" Blood  Bank  Management  System");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 700, 60));

        btn_exit.setBackground(new java.awt.Color(204, 204, 204));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(102, 0, 0));
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 90, 30));

        btn_register.setBackground(new java.awt.Color(204, 204, 204));
        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_register.setForeground(new java.awt.Color(102, 0, 51));
        btn_register.setText("REGISTER");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 110, 30));

        btn_Logintohome.setBackground(new java.awt.Color(204, 204, 204));
        btn_Logintohome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Logintohome.setForeground(new java.awt.Color(102, 0, 0));
        btn_Logintohome.setText("LOGIN");
        btn_Logintohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogintohomeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Logintohome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 140, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\My Java\\BloodBankLogos\\logg02.jpg")); // NOI18N
        jLabel5.setLabelFor(jLabel5);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_upasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_upasswordActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
            // TODO add your handling code here:
        try {
        // Show confirmation dialog to the user
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Exit the application
            System.exit(0);
        }
    } catch (Exception e) {
        // Handle any exceptions that might occur
        javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while trying to exit the application.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
             UserRegister registerForm = new UserRegister();
             registerForm.setVisible(true);
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_LogintohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogintohomeActionPerformed
        // TODO add your handling code here
         if(txt_username.getText().trim().isEmpty() || txt_upassword.getText().trim().isEmpty())
         {
          JOptionPane.showMessageDialog(this, "Please enter User Name or Password", "Warrning", JOptionPane.WARNING_MESSAGE);
          return;
         }
         
         // Database connection
         String dbloc = "jdbc:mysql://localhost/bloodbank"; 
         String dbUname = "root"; 
         String dbpw = ""; 

        // SQL query to check if the username and password exist
         String sql = "SELECT * FROM Staff  WHERE username = ? AND password = ?";
    

        try
        {
            Connection conn = DriverManager.getConnection(dbloc ,dbUname , dbpw);
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_upassword.getText());
            ResultSet rs= pst.executeQuery();
            
            if (rs.next())
            {
             JOptionPane.showMessageDialog(this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
             Homepage hp = new Homepage();
             hp.setVisible(true);
             dispose();
           
            } 
            else {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error! You cannot enter null", JOptionPane.ERROR_MESSAGE);
        }
         
        
       
        
    }//GEN-LAST:event_btn_LogintohomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Logintohome;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_upassword;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
