/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.bank.management.system;

import blood.bank.management.system.Login;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author ACER
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form UserRegister
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_exitRegform = new javax.swing.JButton();
        txt_empname = new javax.swing.JTextField();
        txt_pw = new javax.swing.JTextField();
        txt_staffid = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("User Registration "); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("          Staff Member Register Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 480, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Employee Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Department");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Staff ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 110, 30));

        btn_submit.setBackground(new java.awt.Color(204, 204, 204));
        btn_submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 100, 40));

        btn_exitRegform.setBackground(new java.awt.Color(204, 204, 204));
        btn_exitRegform.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exitRegform.setText("EXIT");
        btn_exitRegform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitRegformActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exitRegform, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 80, 40));

        txt_empname.setBackground(new java.awt.Color(204, 204, 204));
        txt_empname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_empname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 160, 30));

        txt_pw.setBackground(new java.awt.Color(204, 204, 204));
        txt_pw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 160, 30));

        txt_staffid.setBackground(new java.awt.Color(204, 204, 204));
        txt_staffid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_staffid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_staffidActionPerformed(evt);
            }
        });
        getContentPane().add(txt_staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 160, 30));

        txt_department.setBackground(new java.awt.Color(204, 204, 204));
        txt_department.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departmentActionPerformed(evt);
            }
        });
        getContentPane().add(txt_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 160, 30));

        txt_username.setBackground(new java.awt.Color(204, 204, 204));
        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 160, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\My Java\\BloodBankLogos\\b.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
         String dbloc = "jdbc:mysql://localhost/bloodbank"; 
         String dbUname = "root"; 
         String dbpw = ""; 
         
         String staffid=txt_staffid.getText();
         String empname=txt_empname.getText();
         String username=txt_username.getText();
         String password    =txt_pw.getText();
         String department   = txt_department.getText();
         
        String sql=("INSERT INTO Staff Values ('"+staffid+"','"+empname+"','"+username+"','"+password+"','"+department+"')");
          
        try
        {
            Connection conn = DriverManager.getConnection(dbloc ,dbUname , dbpw);
            Statement st = conn.createStatement();
            
            
            int rowsUpdated = st.executeUpdate(sql);
        
              if (rowsUpdated > 0) {
                 JOptionPane.showMessageDialog(this," Submited Staff details successfully!");
                 setVisible(false);
                 
                 } 
                
        }     
        catch(SQLException e)
        {
            System.out.println("Error! Try Again"+e.getMessage());
        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_exitRegformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitRegformActionPerformed
        // TODO add your handling code here:
        try
        {
         int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) 
            {
            Login loginform = new Login();
            loginform.setVisible(true);
            dispose();
            
           }
            if (confirm == javax.swing.JOptionPane.NO_OPTION) 
                    {
                         new UserRegister().setVisible(true);
                    }
                    
        }
        catch(Exception e)
        {
          System.out.println("Error! Try Again" + e.getMessage());
        }
        
    }//GEN-LAST:event_btn_exitRegformActionPerformed

    private void txt_empnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empnameActionPerformed

    private void txt_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwActionPerformed

    private void txt_staffidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_staffidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_staffidActionPerformed

    private void txt_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departmentActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exitRegform;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_empname;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JTextField txt_staffid;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
